name: dora

description: Measure Delivery Performance

inputs:
  token: 
    description: 'Github Token'
    required: true

runs:
  using: node16
  main: dist/index.js

branding:
  color: purple
  icon: bar-chart-2