name: Test DORA
on:
  push:
    branches:
      - main
jobs:
  measure:
    runs-on: ubuntu-latest
    name: Measure Delivery Performance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn
      - name: DORA
        uses: ./.github/actions/dora