name: Test DORA
on:
  push:
    branches:
      - main
jobs:
  measure:
    runs-on: ubuntu-latest
    name: Measure Delivery Performance
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - name: DORA
        uses: ./.github/actions/dora